# Generated by Django 5.1.3 on 2025-02-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldschool_personal_blog', '0002_remove_blogpost_id_blogpost_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='custom_id',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
